name: fitrack
description: "A mobile fitness tracking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  
  # Networking
  dio: ^5.4.2
  
  # Routing
  go_router: ^13.2.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI & Utils
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  camera: ^0.12.0
  intl: any
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  table_calendar: ^3.1.1
  before_after: any
  lucide_icons: any
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
