# Generated by Django 5.1.4 on 2026-04-30 14:06

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_photo_sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('FRONT', 'Front'), ('SIDE', 'Side'), ('BACK', 'Back')], max_length=5)),
                ('image', models.ImageField(upload_to=tracker.models.progress_photo_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracker.progressphotosession')),
            ],
            options={
                'db_table': 'progress_photos',
            },
        ),
        migrations.CreateModel(
            name='WorkoutCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_logged', models.BooleanField(default=False)),
                ('photo_logged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_checkins',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyWeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evening_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_weight_entries',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_weight_per_user_per_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='progressphotosession',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_session_per_user_per_date'),
        ),
        migrations.AddConstraint(
            model_name='progressphoto',
            constraint=models.UniqueConstraint(fields=('session', 'photo_type'), name='unique_photo_type_per_session'),
        ),
        migrations.AddConstraint(
            model_name='workoutcheckin',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_checkin_per_user_per_date'),
        ),
    ]
