# Generated by Django 5.1.4 on 2026-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweightentry',
            name='evening_weight_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyweightentry',
            name='morning_weight_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
