# Generated by Django 5.1.4 on 2026-05-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailyweightentry_evening_weight_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('LOSE', 'Lose Weight'), ('GAIN', 'Gain Weight')], max_length=4)),
                ('target_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_goals',
            },
        ),
    ]
