# Generated by Django 5.1.4 on 2026-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_weightgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightgoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
