# Generated by Django 5.1.4 on 2026-05-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_weightgoal_current_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightgoal',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
