# Generated by Django 5.1.4 on 2026-05-08 07:20

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_weightgoal_current_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressphoto',
            name='crop_aspect_ratio',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='crop_offset_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='crop_offset_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='crop_scale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='normalized_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.models.normalized_photo_upload_path),
        ),
    ]
