# Generated by Django 5.1.4 on 2026-05-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_progressphoto_crop_aspect_ratio_and_more'),
        ('tracker', '0008_userconsent_userkyc'),
    ]

    operations = [
    ]
